version: "3"
services:
  web:
    build: .
    environment:
      REDIS_HOST: 'redis'
    volumes:
      - .:/usr/src/app
    depends_on:
      - "database"
    ports:
      - "5000:5000"
    command: ["./wait-for-it.sh", "database:5432", "--", "npm", "start"]
  redis:
    image: redis
  database:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
    env_file:
      - db.env
